### PR TITLE
Solution Regex exercise 1

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**

### CODE REVIEW

**Comment by gauthamzz** [comment]
Finally 👍 yaay

**Comment by mubaris** [comment]
@GOVINDDIXIT Try to implement it in Go and JS. It's very easy

**Comment by GOVINDDIXIT** [comment]
@mubaris Do we get extra points for solving this in different languages

**Comment by mubaris** [comment]
Yep

**Comment by mubaris** [comment]
More languages => More Points

**Pull request merged**
