### PR TITLE
Added Image manipulation script

### PR DESCRIPTION
**Pull request by Jigar3**

### CODE REVIEW

**Review by gauthamzz — CHANGES_REQUESTED** [review]
Take text values from a file , you need to use io. And do a loop

**Comment by Jigar3** [comment]
loop for what? didnt understand

**Comment by gauthamzz** [comment]
The text which is added is in a file and file is like
Name 1
Name 2 
Name 3 
.
.

**Comment by Jigar3** [comment]
@gauthamzz  please review

**Review by gauthamzz — APPROVED** [review]

**Pull request merged**
