### PR TITLE
added task4 solution

### PR DESCRIPTION
**Pull request by rudransh1**
issue #12 
@gauthamzz

### CODE REVIEW

**Review by gauthamzz — CHANGES_REQUESTED** [review]
Wtf turtle are you in high school

**Comment by rudransh1** [comment]
sorry for that 😮

**Comment by gauthamzz** [comment]
Come on kids use that. Make good pr with effort. Learn something new. Else what’s the purpose of this . It’s not a big prize money. Put more time into issues. Anyway you did great till now , keep up the effort.

**Comment by rudransh1** [comment]
I understand... I will keep that in mind for future!

**Pull request closed without merging**
