### PR TITLE
Added solution to Task2

### PR DESCRIPTION
**Pull request by prathamprakash29**

### CODE REVIEW

**Comment by mubaris** [comment]
@prathamprakash29 This looks copied

CC - @gauthamzz

**Comment by gauthamzz** [comment]
We are not saying you copied it, but you submitted very late. But If you did it yourself , it won’t take much time to do it in an another language . Try it in something other than python and send pr

**Comment by mubaris** [comment]
@prathamprakash29 Try Ruby. It's very similar

**Comment by gauthamzz** [comment]
Try to solve this befor other issues as we will be looking forward to your PR 😛😇

**Pull request closed without merging**
