### PR TITLE
task2 solution added

### PR DESCRIPTION
**Pull request by pani-vishal**
#2 solution added

### CODE REVIEW

**Comment by mubaris** [comment]
@falconis Try to implement it in Go and JS. It's very easy

**Comment by pani-vishal** [comment]
Sure! Will do.

**Comment by pani-vishal** [comment]
In the JS implementation, do I have to provide a html file and link the js to it? :sweat_smile:

**Comment by mubaris** [comment]
Use Node.js

**Comment by pani-vishal** [comment]
I don't know node.js right now, so can I just use prompt function for now.
I'll use node.js for future problems.

**Comment by mubaris** [comment]
Node.js is basically JS without the need for HTML, at least for this task.

Try it. If you implement it, we'll give you extra 10 points 😄

**Comment by pani-vishal** [comment]
Alright! I'll give it a shot.

**Pull request merged**
