### PR TITLE
Solution to tasks 1,3,4,5,6,7 and 9 added

### PR DESCRIPTION
**Pull request by pani-vishal**
Related to issues #1 #11 #12 #13 #21 #32 #49.

### CODE REVIEW

**Comment by gauthamzz** [comment]
only change your files.
Fix the codacy issues.

**Comment by Anupam-dagar** [comment]
why are there 94 file changes?
please make changes to only your files

**Comment by pani-vishal** [comment]
I don't know what happened. I'll send a PR after sometime.

**Comment by pani-vishal** [comment]
Pls review @gauthamzz. The only check which failed is telling me to avoid using urllib.urlopen, so should I try something else?
Because the program is working fine when I use it.

**Comment by gauthamzz** [comment]
It’s failing checks , won’t review if it doesn’t pass checks

**Review by mubaris — APPROVED** [review]

**Pull request merged**
